version: v1.0.0
policy: deny_by_default

# Runtime routing configuration
# Defines which components can communicate with each other
# ALL routes must be explicitly defined - deny by default
# Theme 8 & 9: Minimal edges only for system closure

routes:
  # Main UI to Backend UI (only allowed UI-to-module edge)
  - id: main-ui-to-backend-ui
    from:
      type: ui
      id: main_ui
    to:
      type: module
      id: backend-ui
    conditions:
      scopes:
        - ui:access
      roles:
        - admin
        - editor
        - viewer
    metadata:
      description: "Allow main UI to access backend_ui gateway only"
      enabled: true
      priority: 100
  
  # Backend UI to Ads API Parser (example module invocation)
  - id: backend-ui-to-ads-parser
    from:
      type: module
      id: backend-ui
    to:
      type: module
      id: ads-api-parser
    conditions:
      scopes:
        - storage:write
      roles:
        - admin
        - editor
    metadata:
      description: "Allow backend_ui to invoke ads_api_parser"
      enabled: true
      priority: 50

# Global routing restrictions
restrictions:
  max_chain_depth: 5
  
  # Capabilities that are globally blocked from direct invocation
  blocked_capabilities:
    - system.shutdown
    - kernel.debug
    - kernel.config.modify
  
  # Network segments allowed for communication
  allowed_networks:
    - mesh    # Internal module-to-module
    - edge    # UI-to-platform
